/*
 * The HR/Admin payroll grid — was `(hr)/(tabs)/index.tsx`, the Payroll tab,
 * before HR-ADMIN-MOBILE-ACCESS-ADDENDUM.md narrowed HR/Admin's mobile
 * surface. This screen belongs to the full HR/Admin surface, which lives on
 * the web dashboard, in `WebShell`'s nav under "payroll-grid" (linked since
 * HR-DASHBOARD-RELOCATION-PROPOSAL.md's Stage A — Stage C turned out already
 * satisfied by that same pass, see CLAUDE.md's "HR full-dashboard Stages
 * B-D"; this file's own header comment saying otherwise was simply never
 * updated after the fact).
 *
 * Its data layer: run/payslip reads and writes (status advancement,
 * mark-paid, proof attachment) go through `waa-hr-payroll-grid`
 * (company-scoped edge function). The leave-overlap flag per worker keeps
 * its own separately-fixed path — see
 * `waa_worker_has_leave_overlap_for_caller` in CLAUDE.md — unchanged here.
 */
import React, { useMemo, useState } from 'react';
import {
  Alert,
  Modal,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import DateTimePicker from '@react-native-community/datetimepicker';
import { router } from 'expo-router';
import { useHrAdmin } from '../../src/lib/session';
import { useAsync } from '../../src/lib/useAsync';
import {
  attachPayslipProof,
  fetchAllCashAdvances,
  fetchPayrollRuns,
  fetchPayrollSettings,
  fetchPayslipsForRun,
  fetchProjects,
  fetchWorkerLeaveOverlapFlag,
  generatePayrollRun,
  markPayrollRunPaid,
  setPayrollRunStatus,
} from '../../src/lib/queries';
import type { PayrollRunStatus, WaaPayslipDetailed } from '../../src/lib/types';
import { captureDocument, pickImageFromLibrary } from '../../src/lib/capture';
import { uploadToPath } from '../../src/lib/storage';
import {
  Card,
  EmptyState,
  ErrorNote,
  Loader,
  Pill,
} from '../../src/components/ui';
import { colors, fonts, radius, spacing, toneForStatus, type } from '../../src/theme';
import { cutoffFor, hours, periodLabel, peso, toDateColumn } from '../../src/lib/format';
import { WebShell } from '../../src/web/WebShell';
import { useWebTheme, webOnlyStyle } from '../../src/web/webTheme';
import { Chip, GlassButton, GlassOutlineButton, MetricCard, WebPageHeader, WebPill, WebSection } from '../../src/web/webUi';
import { CheckIcon, PayslipIcon, XIcon } from '../../src/components/icons';

/** The lifecycle, in order. `paid` is handled separately — it needs proofs first. */
const NEXT_STATUS: Record<PayrollRunStatus, PayrollRunStatus | null> = {
  draft: 'reviewed',
  reviewed: 'finalized',
  finalized: 'paid',
  paid: null,
};

const STATUS_ACTION: Record<string, string> = {
  reviewed: 'Mark reviewed',
  finalized: 'Finalize',
  paid: 'Mark paid',
};

/**
 * HR/Admin Payroll tab — the module's main surface.
 *
 * Runs are generated by the `waa-generate-payroll-run` edge function (the pay
 * math lives there, in one place, not duplicated here). Status advancement is
 * a plain UPDATE: the gates are DB triggers, so a blocked transition comes
 * back as a Postgres exception whose message is written for a human, and is
 * surfaced verbatim rather than replaced with a generic failure.
 */
export default function HrPayroll() {
  const hrAdmin = useHrAdmin();
  const { palette } = useWebTheme();
  /** Grid-specific styling — the dense worker-by-worker table this screen's
   * main data lives in used to be plain white (`colors.paper`) even after
   * everything around it went glass. Kept separate from the static `s`
   * StyleSheet below (which still covers layout-only concerns and the
   * deliberately-left-white run-summary/breakdown/modal cards) because these
   * few keys need to repaint with the live theme. */
  const gs = useMemo(
    () => ({
      row: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderBottomWidth: 1,
        borderBottomColor: palette.border,
      },
      // nexus-hris.html's th treatment: an uppercase, letter-spaced label on
      // a distinct (not just "hover-tint") header band that stays pinned
      // while the grid's own body scrolls under it.
      headRow: { backgroundColor: palette.bg2, ...webOnlyStyle({ position: 'sticky', top: 0, zIndex: 2 }) },
      subtotalRow: { backgroundColor: palette.hover, borderBottomWidth: 0 },
      headText: {
        fontSize: 9,
        letterSpacing: 0.8,
        textTransform: 'uppercase' as const,
        color: palette.muted2,
        fontWeight: '800' as const,
      },
      name: { fontSize: 12.5, fontWeight: '700' as const, color: palette.text },
      sub: { fontSize: 10.5, color: palette.muted },
      body: { fontSize: 12, color: palette.text, fontVariant: ['tabular-nums'] as ('tabular-nums')[] },
      strong: { fontWeight: '700' as const, color: palette.text, fontVariant: ['tabular-nums'] as ('tabular-nums')[] },
    }),
    [palette]
  );
  const [selectedRunId, setSelectedRunId] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [uploadingFor, setUploadingFor] = useState<string | null>(null);

  // Period pickers, defaulted to the configured cutoff cadence.
  const [range, setRange] = useState<{ from: Date; to: Date } | null>(null);
  const [picking, setPicking] = useState<'from' | 'to' | null>(null);
  const [showGenerator, setShowGenerator] = useState(false);

  const { data, loading, reload } = useAsync(async () => {
    const [settings, runs, projects, advances] = await Promise.all([
      fetchPayrollSettings(),
      fetchPayrollRuns(),
      fetchProjects(),
      fetchAllCashAdvances(),
    ]);

    const activeRunId = selectedRunId ?? runs[0]?.id ?? null;
    const payslips = activeRunId ? await fetchPayslipsForRun(activeRunId) : [];

    // The same function the draft -> reviewed trigger calls, so the Flags
    // column shows exactly what will block the run.
    const flagPairs = await Promise.all(
      payslips.map(async (p) => {
        const flagged = await fetchWorkerLeaveOverlapFlag(p.worker_id).catch(() => false);
        return [p.worker_id, flagged] as const;
      })
    );
    const flags = new Map<string, boolean>(flagPairs);

    return { settings, runs, projects, advances, activeRunId, payslips, flags };
  }, [hrAdmin.id, selectedRunId]);

  const run = useMemo(
    () => data?.runs.find((r) => r.id === data.activeRunId) ?? null,
    [data]
  );

  const projectName = useMemo(() => {
    const map = new Map<string, string>();
    for (const p of data?.projects ?? []) map.set(p.id, p.name);
    return map;
  }, [data?.projects]);

  /** Grid grouped by site, then position, with a subtotal per site. */
  const groups = useMemo(() => {
    const bySite = new Map<string, WaaPayslipDetailed[]>();
    for (const slip of data?.payslips ?? []) {
      const site = slip.worker?.current_project_id
        ? (projectName.get(slip.worker.current_project_id) ?? 'Unassigned site')
        : 'Unassigned site';
      bySite.set(site, [...(bySite.get(site) ?? []), slip]);
    }
    return Array.from(bySite.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([site, slips]) => ({
        site,
        slips: slips.slice().sort((a, b) => {
          const pa = a.worker?.position ?? '';
          const pb = b.worker?.position ?? '';
          if (pa !== pb) return pa.localeCompare(pb);
          return (a.worker?.full_name ?? '').localeCompare(b.worker?.full_name ?? '');
        }),
        subtotal: slips.reduce((sum, s2) => sum + Number(s2.net_pay), 0),
        gross: slips.reduce((sum, s2) => sum + Number(s2.gross_pay), 0),
      }));
  }, [data?.payslips, projectName]);

  const grandTotal = (data?.payslips ?? []).reduce((sum, s2) => sum + Number(s2.net_pay), 0);
  const missingProof = (data?.payslips ?? []).filter((s2) => !s2.proof_url);
  const pendingAdvances = (data?.advances ?? []).filter(
    (a) => a.status === 'pending' || a.status === 'approved'
  );

  function openGenerator() {
    const window = cutoffFor(data?.settings?.cutoff_type ?? 'semi_monthly');
    setRange({ from: window.start, to: window.end });
    setError(null);
    setShowGenerator(true);
  }

  async function doGenerate() {
    if (!range) return;
    setGenerating(true);
    setError(null);
    try {
      const result = await generatePayrollRun(
        toDateColumn(range.from),
        toDateColumn(range.to)
      );
      setShowGenerator(false);
      setSelectedRunId(result.payroll_run_id);
      await reload();
      Alert.alert(
        'Draft run ready',
        `${result.worker_count} worker${result.worker_count === 1 ? '' : 's'} included.`
      );
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not generate the run.');
    } finally {
      setGenerating(false);
    }
  }

  /**
   * Advances the run one step. Everything except `paid` is a bare status
   * update; `paid` goes through `markPayrollRunPaid`, which stamps the
   * payslips once the DB accepts the transition so the slips become visible
   * on each worker's own Pay tab.
   */
  async function advance(next: PayrollRunStatus) {
    if (!run) return;

    if (next === 'paid' && missingProof.length > 0) {
      Alert.alert(
        'Proof of payment missing',
        `${missingProof.length} worker${
          missingProof.length === 1 ? ' is' : 's are'
        } still without a proof attachment. Attach one per worker below — the database rejects the whole run otherwise.`
      );
      return;
    }

    setBusy(true);
    setError(null);
    try {
      if (next === 'paid') await markPayrollRunPaid(run.id);
      else await setPayrollRunStatus(run.id, next);
      await reload();
    } catch (e) {
      // These are the DB trigger messages — written to be read, so shown as-is.
      setError(e instanceof Error ? e.message : 'Could not change the run status.');
    } finally {
      setBusy(false);
    }
  }

  function attachProof(slip: WaaPayslipDetailed) {
    Alert.alert('Attach proof of payment', 'Where is the proof?', [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Take photo', onPress: () => doAttach(slip, 'camera') },
      { text: 'Choose from photos', onPress: () => doAttach(slip, 'library') },
    ]);
  }

  async function doAttach(slip: WaaPayslipDetailed, source: 'camera' | 'library') {
    const uri = source === 'camera' ? await captureDocument() : await pickImageFromLibrary();
    if (!uri) return;
    setUploadingFor(slip.id);
    try {
      // Path convention is load-bearing: the bucket's worker-read policy
      // matches on `payslip/{worker_id}/…`.
      const path = await uploadToPath(
        'waa-payroll-proofs',
        `payslip/${slip.worker_id}/${slip.payroll_run_id}`,
        uri,
        'proof'
      );
      await attachPayslipProof(slip.id, path);
      await reload();
    } catch (e) {
      Alert.alert('Upload failed', e instanceof Error ? e.message : 'Try again.');
    } finally {
      setUploadingFor(null);
    }
  }

  const next = run ? NEXT_STATUS[run.status] : null;

  return (
    <WebShell
      active="payroll-grid"
      title="Payroll"
      subtitle={`Every site, every active worker · ${data?.settings?.cutoff_type.replace('_', '-') ?? '—'} cutoff`}
    >
        <WebPageHeader
          eyebrow="Workforce"
          title="Payroll"
          sub={`Every site, every active worker · ${data?.settings?.cutoff_type.replace('_', '-') ?? '—'} cutoff.`}
        />

        {error ? <ErrorNote message={error} /> : null}

        {/* nexus's `.toolbar`: one compact row of inline actions, primary
            first — not three stacked full-width slabs above the data. */}
        <View style={s.actionRow}>
          <GlassButton
            label={run?.status === 'draft' ? '▶ Regenerate run' : '▶ Start a run'}
            onPress={openGenerator}
            size="sm"
            block={false}
          />
          <GlassOutlineButton
            label={`Advances${pendingAdvances.length ? ` (${pendingAdvances.length})` : ''}`}
            onPress={() => router.push('/(hr)/cash-advances')}
            size="sm"
            block={false}
          />
          <GlassOutlineButton
            label="⚙ Payroll settings"
            onPress={() => router.push('/(hr)/settings')}
            size="sm"
            block={false}
          />
        </View>

        {loading && !data ? (
          <Loader label="Loading runs" />
        ) : (data?.runs.length ?? 0) === 0 ? (
          <EmptyState
            title="No payroll runs yet"
            body="Start a run for a period — every active worker's punches, leave and advances are pulled in automatically."
          />
        ) : (
          <>
            {/* --------------------------- Run picker ------------------- */}
            <View style={s.filterRow}>
              {data!.runs.map((r) => {
                const active = r.id === data!.activeRunId;
                return (
                  <Chip
                    key={r.id}
                    label={periodLabel(r.period_start, r.period_end)}
                    active={active}
                    onPress={() => {
                      setSelectedRunId(r.id);
                      setExpanded(null);
                      setError(null);
                    }}
                  />
                );
              })}
            </View>

            {run ? (
              <>
                <Card style={s.runCard}>
                  <View style={s.runHead}>
                    <View style={{ flex: 1 }}>
                      <Text style={s.runPeriod}>
                        {periodLabel(run.period_start, run.period_end)}
                      </Text>
                      <Text style={s.runSub}>
                        {data!.payslips.length} worker
                        {data!.payslips.length === 1 ? '' : 's'} · net {peso(grandTotal)}
                      </Text>
                    </View>
                    <Pill label={run.status} tone={toneForStatus(run.status)} />
                  </View>

                  {next ? (
                    <GlassButton
                      label={busy ? 'Saving…' : (STATUS_ACTION[next] ?? 'Advance')}
                      onPress={() => advance(next)}
                      loading={busy}
                      tone={next === 'paid' ? 'good' : 'accent'}
                      style={{ marginTop: 14 }}
                    />
                  ) : (
                    <Text style={s.runDone}>
                      This run is closed. Its payslips are visible to each worker.
                    </Text>
                  )}

                  {run.status === 'finalized' && missingProof.length > 0 ? (
                    <Text style={s.runWarn}>
                      {missingProof.length} of {data!.payslips.length} payslips still need a proof
                      attachment before this run can be marked paid.
                    </Text>
                  ) : null}
                </Card>

                <View style={s.statGrid}>
                  <MetricCard
                    style={s.statItem}
                    icon={<PayslipIcon color={palette.info} size={17} />}
                    iconBg={palette.infoBg}
                    label="Payslips"
                    value={data!.payslips.length.toLocaleString()}
                    trendPct={null}
                  />
                  <MetricCard
                    style={s.statItem}
                    icon={<CheckIcon color={palette.good} size={17} />}
                    iconBg={palette.goodBg}
                    label="Proof attached"
                    value={data!.payslips.filter((p) => p.proof_url).length.toLocaleString()}
                    trendPct={null}
                  />
                  <MetricCard
                    style={s.statItem}
                    icon={<XIcon color={missingProof.length > 0 ? palette.bad : palette.muted} size={17} />}
                    iconBg={missingProof.length > 0 ? palette.badBg : palette.hover}
                    label="Missing proof"
                    value={missingProof.length.toLocaleString()}
                    trendPct={null}
                  />
                </View>

                {/* ------------------------ The grid --------------------- */}
                {data!.payslips.length === 0 ? (
                  <EmptyState
                    title="This run has no payslips"
                    body="Regenerate it, or check that there are active workers with approved punches in the period."
                  />
                ) : (
                  groups.map((g) => (
                    <WebSection key={g.site} title={g.site}>
                      <View style={[s.tableWrap, { borderColor: palette.border, backgroundColor: palette.panelSolid }]}>
                        <ScrollView horizontal showsHorizontalScrollIndicator={false}>
                          <View>
                            <View style={[gs.row, gs.headRow]}>
                              <Text style={[s.cell, s.cWorker, gs.headText]}>Worker</Text>
                              <Text style={[s.cell, s.cNum, gs.headText]}>Days</Text>
                              <Text style={[s.cell, s.cNum, gs.headText]}>Hours</Text>
                              <Text style={[s.cell, s.cNum, gs.headText]}>OT hrs</Text>
                              <Text style={[s.cell, s.cNum, gs.headText]}>Paid lv</Text>
                              <Text style={[s.cell, s.cNum, gs.headText]}>Unpaid lv</Text>
                              <Text style={[s.cell, s.cMoney, gs.headText]}>Regular</Text>
                              <Text style={[s.cell, s.cMoney, gs.headText]}>Overtime</Text>
                              <Text style={[s.cell, s.cMoney, gs.headText]}>Leave pay</Text>
                              <Text style={[s.cell, s.cMoney, gs.headText]}>Gross</Text>
                              <Text style={[s.cell, s.cMoney, gs.headText]}>Cash adv.</Text>
                              <Text style={[s.cell, s.cMoney, gs.headText]}>Statutory</Text>
                              <Text style={[s.cell, s.cMoney, gs.headText]}>Net pay</Text>
                              <Text style={[s.cell, s.cStatus, gs.headText]}>Run status</Text>
                              <Text style={[s.cell, s.cProof, gs.headText]}>Proof</Text>
                              <Text style={[s.cell, s.cProof, gs.headText]}>Flags</Text>
                            </View>

                            {g.slips.map((p, i) => {
                              const statutory =
                                Number(p.sss_deducted) +
                                Number(p.pagibig_deducted) +
                                Number(p.philhealth_deducted) +
                                Number(p.withholding_tax_deducted);
                              return (
                                <Pressable
                                  key={p.id}
                                  onPress={() => setExpanded(expanded === p.id ? null : p.id)}
                                  style={({ pressed }) => [
                                    gs.row,
                                    i === g.slips.length - 1 && s.rowLast,
                                    pressed && { backgroundColor: palette.hover },
                                  ]}
                                >
                                  <View style={[s.cell, s.cWorker]}>
                                    <Text style={gs.name} numberOfLines={1}>
                                      {p.worker?.full_name ?? 'Worker'}
                                    </Text>
                                    <Text style={gs.sub} numberOfLines={1}>
                                      {p.worker?.position || 'No position'}
                                    </Text>
                                  </View>
                                  <Text style={[s.cell, s.cNum, gs.body]}>
                                    {estimateDays(p.worked_hours, data!.settings?.standard_hours_per_day)}
                                  </Text>
                                  <Text style={[s.cell, s.cNum, gs.body]}>
                                    {Number(p.worked_hours).toFixed(2)}
                                  </Text>
                                  <Text style={[s.cell, s.cNum, gs.body]}>
                                    {Number(p.overtime_hours).toFixed(2)}
                                  </Text>
                                  <Text style={[s.cell, s.cNum, gs.body]}>
                                    {paidLeaveDays(p.paid_leave_hours, data!.settings?.standard_hours_per_day)}
                                  </Text>
                                  <Text style={[s.cell, s.cNum, gs.body]}>
                                    {Number(p.unpaid_leave_days)}
                                  </Text>
                                  <Text style={[s.cell, s.cMoney, gs.body]}>
                                    {peso(p.regular_pay)}
                                  </Text>
                                  <Text style={[s.cell, s.cMoney, gs.body]}>
                                    {peso(p.overtime_pay)}
                                  </Text>
                                  <Text style={[s.cell, s.cMoney, gs.body]}>{peso(p.leave_pay)}</Text>
                                  <Text style={[s.cell, s.cMoney, gs.strong]}>
                                    {peso(p.gross_pay)}
                                  </Text>
                                  <Text style={[s.cell, s.cMoney, gs.body]}>
                                    {peso(p.cash_advance_deducted)}
                                  </Text>
                                  <Text style={[s.cell, s.cMoney, gs.body]}>{peso(statutory)}</Text>
                                  <Text style={[s.cell, s.cMoney, gs.strong]}>{peso(p.net_pay)}</Text>
                                  <Text style={[s.cell, s.cStatus, gs.sub]}>{run.status}</Text>
                                  <View style={[s.cell, s.cProof]}>
                                    {p.proof_url ? (
                                      <WebPill label="Yes" tone="good" />
                                    ) : (
                                      <WebPill label="—" tone="muted" />
                                    )}
                                  </View>
                                  <View style={[s.cell, s.cProof]}>
                                    {data!.flags.get(p.worker_id) ? (
                                      <WebPill label="Overlap" tone="bad" />
                                    ) : (
                                      <Text style={gs.sub}>—</Text>
                                    )}
                                  </View>
                                </Pressable>
                              );
                            })}

                            <View style={[gs.row, gs.subtotalRow]}>
                              <Text style={[s.cell, s.cWorker, gs.strong]}>{g.site} subtotal</Text>
                              <Text style={[s.cell, s.cNum]} />
                              <Text style={[s.cell, s.cNum]} />
                              <Text style={[s.cell, s.cNum]} />
                              <Text style={[s.cell, s.cNum]} />
                              <Text style={[s.cell, s.cNum]} />
                              <Text style={[s.cell, s.cMoney]} />
                              <Text style={[s.cell, s.cMoney]} />
                              <Text style={[s.cell, s.cMoney]} />
                              <Text style={[s.cell, s.cMoney, gs.strong]}>{peso(g.gross)}</Text>
                              <Text style={[s.cell, s.cMoney]} />
                              <Text style={[s.cell, s.cMoney]} />
                              <Text style={[s.cell, s.cMoney, gs.strong]}>{peso(g.subtotal)}</Text>
                              <Text style={[s.cell, s.cStatus]} />
                              <Text style={[s.cell, s.cProof]} />
                              <Text style={[s.cell, s.cProof]} />
                            </View>
                          </View>
                        </ScrollView>
                      </View>

                      {/* Expanded breakdown for whichever row was tapped. */}
                      {g.slips
                        .filter((p) => p.id === expanded)
                        .map((p) => (
                          <Breakdown
                            key={`x-${p.id}`}
                            slip={p}
                            uploading={uploadingFor === p.id}
                            onAttachProof={() => attachProof(p)}
                          />
                        ))}
                    </WebSection>
                  ))
                )}

                {data!.payslips.length > 0 ? (
                  <View
                    style={[
                      s.totalCard,
                      { backgroundColor: palette.panelSolid, borderColor: palette.border },
                      webOnlyStyle({ backgroundImage: `linear-gradient(135deg, ${palette.accent}, ${palette.accent2})` }),
                    ]}
                  >
                    <Text style={[s.totalLabel, { color: 'rgba(255,255,255,0.8)' }]}>Grand total · net pay</Text>
                    <Text style={s.totalValue}>{peso(grandTotal)}</Text>
                  </View>
                ) : null}
              </>
            ) : null}
          </>
        )}

      {/* --------------------------- Run generator ---------------------- */}
      <Modal
        visible={showGenerator}
        transparent
        animationType="slide"
        onRequestClose={() => setShowGenerator(false)}
      >
        <Pressable style={s.backdrop} onPress={() => setShowGenerator(false)}>
          <Pressable style={s.sheet} onPress={(e) => e.stopPropagation()}>
            <ScrollView contentContainerStyle={{ padding: spacing.xl, paddingBottom: 40 }}>
              <Text style={s.sheetTitle}>Generate a payroll run</Text>
              <Text style={s.sheetSub}>
                Pulls every active worker's approved punches, approved leave, rate, deduction
                overrides and leave-pay settings for the period. Re-running a draft wipes and
                recomputes it.
              </Text>

              {error ? <ErrorNote message={error} /> : null}

              <View style={s.dateRow}>
                <DateBox
                  label="Period start"
                  value={range?.from ?? new Date()}
                  onPress={() => setPicking('from')}
                />
                <DateBox
                  label="Period end"
                  value={range?.to ?? new Date()}
                  onPress={() => setPicking('to')}
                />
              </View>

              {picking && range ? (
                <DateTimePicker
                  value={picking === 'from' ? range.from : range.to}
                  mode="date"
                  display={Platform.OS === 'ios' ? 'inline' : 'default'}
                  minimumDate={picking === 'to' ? range.from : undefined}
                  onChange={(_e, picked) => {
                    if (Platform.OS === 'android') setPicking(null);
                    if (!picked) return;
                    setRange((prev) => {
                      if (!prev) return prev;
                      if (picking === 'from') {
                        return { from: picked, to: prev.to < picked ? picked : prev.to };
                      }
                      return { ...prev, to: picked };
                    });
                  }}
                />
              ) : null}
              {picking && Platform.OS === 'ios' ? (
                <Pressable onPress={() => setPicking(null)} style={s.doneBtn}>
                  <Text style={s.doneText}>Done</Text>
                </Pressable>
              ) : null}

              <GlassButton
                label={generating ? 'Generating…' : 'Generate'}
                onPress={doGenerate}
                loading={generating}
                style={{ marginTop: spacing.md }}
              />
              <GlassOutlineButton
                label="Cancel"
                onPress={() => setShowGenerator(false)}
                style={{ marginTop: 10 }}
              />
            </ScrollView>
          </Pressable>
        </Pressable>
      </Modal>
    </WebShell>
  );
}

/**
 * Days aren't stored on the payslip — the engine only writes hours — so the
 * grid derives them from worked hours against the standard day. Labelled
 * "Days" per the brief's column list; the authoritative figures are the hours.
 */
function estimateDays(workedHours: number, standard: number | undefined): string {
  const std = Number(standard ?? 8);
  if (!std) return '—';
  const days = Number(workedHours) / std;
  return days === Math.round(days) ? String(days) : days.toFixed(1);
}

function paidLeaveDays(paidLeaveHours: number, standard: number | undefined): string {
  const std = Number(standard ?? 8);
  if (!std) return '—';
  const days = Number(paidLeaveHours) / std;
  return days === Math.round(days) ? String(days) : days.toFixed(1);
}

/** The per-line breakdown, with Statutory split into its four components. */
function Breakdown({
  slip,
  uploading,
  onAttachProof,
}: {
  slip: WaaPayslipDetailed;
  uploading: boolean;
  onAttachProof: () => void;
}) {
  return (
    <Card style={s.breakdown}>
      <Text style={s.breakdownTitle}>{slip.worker?.full_name ?? 'Worker'}</Text>
      <Text style={s.breakdownSub}>{slip.worker?.position || 'No position set'}</Text>

      <Line label="Worked" note={hours(slip.worked_hours)} amount={slip.regular_pay} />
      <Line label="Overtime" note={hours(slip.overtime_hours)} amount={slip.overtime_pay} />
      <Line label="Paid leave" note={hours(slip.paid_leave_hours)} amount={slip.leave_pay} />
      <Line
        label="Unpaid leave"
        note={`${slip.unpaid_leave_days} day${Number(slip.unpaid_leave_days) === 1 ? '' : 's'}`}
        amount={0}
      />
      <View style={s.rule} />
      <Line label="Gross pay" amount={slip.gross_pay} strong />
      <View style={s.rule} />
      <Line label="Cash advance" amount={-Number(slip.cash_advance_deducted)} />
      <Line label="SSS" amount={-Number(slip.sss_deducted)} />
      <Line label="Pag-IBIG" amount={-Number(slip.pagibig_deducted)} />
      <Line label="PhilHealth" amount={-Number(slip.philhealth_deducted)} />
      <Line label="Withholding tax" amount={-Number(slip.withholding_tax_deducted)} />
      <View style={s.rule} />
      <Line label="Net pay" amount={slip.net_pay} strong />

      {slip.proof_url ? (
        <Text style={s.proofOk}>Proof of payment attached.</Text>
      ) : (
        <GlassOutlineButton
          label={uploading ? 'Uploading…' : 'Attach proof of payment'}
          onPress={onAttachProof}
          disabled={uploading}
          style={{ marginTop: 14 }}
        />
      )}
    </Card>
  );
}

function Line({
  label,
  note,
  amount,
  strong,
}: {
  label: string;
  note?: string;
  amount: number;
  strong?: boolean;
}) {
  const n = Number(amount);
  return (
    <View style={s.line}>
      <View style={{ flex: 1 }}>
        <Text style={[s.lineLabel, strong && s.strong]}>{label}</Text>
        {note ? <Text style={s.lineNote}>{note}</Text> : null}
      </View>
      <Text style={[s.lineAmount, strong && s.strong, n < 0 && { color: colors.warn }]}>
        {n < 0 ? `−${peso(Math.abs(n))}` : peso(n)}
      </Text>
    </View>
  );
}

function DateBox({ label, value, onPress }: { label: string; value: Date; onPress: () => void }) {
  return (
    <Pressable style={s.dateBox} onPress={onPress}>
      <Text style={[type.label, { marginBottom: 4 }]}>{label}</Text>
      <Text style={s.dateValue}>
        {value.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}
      </Text>
    </Pressable>
  );
}

const s = StyleSheet.create({
  statGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, marginBottom: 18 },
  statItem: { flexGrow: 1, flexBasis: 180, minWidth: 160 },
  actionRow: { flexDirection: 'row', gap: 9, marginBottom: 15, flexWrap: 'wrap', alignItems: 'center' },
  filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 18 },

  runCard: { marginBottom: 18 },
  runHead: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  runPeriod: { fontFamily: fonts.serif, fontSize: 19, fontWeight: '700', color: colors.ink },
  runSub: { fontSize: 12, color: colors.muted, marginTop: 2, fontFamily: fonts.body },
  runDone: { fontSize: 11.5, color: colors.ok, marginTop: 12, fontFamily: fonts.bodySemi },
  runWarn: { fontSize: 11.5, color: colors.warn, marginTop: 10, lineHeight: 17, fontFamily: fonts.body },

  tableWrap: { borderWidth: 1, borderRadius: 15, overflow: 'hidden' },
  rowLast: { borderBottomWidth: 0 },
  cell: { paddingRight: 12 },
  cWorker: { width: 140 },
  cNum: { width: 54, textAlign: 'right' },
  cMoney: { width: 82, textAlign: 'right' },
  cStatus: { width: 74 },
  cProof: { width: 58 },

  breakdown: { marginTop: 10, backgroundColor: colors.paper, borderColor: colors.line },
  breakdownTitle: { fontSize: 14, fontFamily: fonts.bodyBold, color: colors.ink },
  breakdownSub: { fontSize: 11.5, color: colors.muted, marginBottom: 8, fontFamily: fonts.body },
  line: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 5 },
  lineLabel: { fontSize: 12.5, color: colors.ink, fontFamily: fonts.body },
  lineNote: { fontSize: 10.5, color: colors.muted, fontFamily: fonts.body },
  lineAmount: { fontSize: 12.5, color: colors.ink, fontFamily: fonts.bodySemi },
  strong: { fontFamily: fonts.bodyBold, color: colors.ink },
  rule: { height: 1, backgroundColor: colors.line, marginVertical: 6 },
  proofOk: { fontSize: 11.5, color: colors.ok, marginTop: 12, fontFamily: fonts.bodySemi },

  totalCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 18,
    gap: 3,
    marginBottom: 30,
  },
  totalLabel: {
    fontSize: 10.5,
    letterSpacing: 1,
    fontFamily: fonts.bodySemi,
  },
  totalValue: { fontFamily: fonts.serif, fontSize: 30, fontWeight: '700', color: '#fff' },

  backdrop: { flex: 1, backgroundColor: 'rgba(28,27,24,0.5)', justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: colors.paper,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    maxHeight: '85%',
  },
  sheetTitle: { fontFamily: fonts.serif, fontSize: 22, fontWeight: '700', color: colors.ink },
  sheetSub: {
    fontSize: 12.5,
    color: colors.muted,
    lineHeight: 18,
    marginTop: 4,
    marginBottom: spacing.lg,
    fontFamily: fonts.body,
  },
  dateRow: { flexDirection: 'row', gap: 10, marginBottom: spacing.md },
  dateBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.lg,
    padding: 12,
    backgroundColor: colors.card,
  },
  dateValue: { fontSize: 13.5, fontFamily: fonts.bodySemi, color: colors.ink },
  doneBtn: { alignSelf: 'flex-end', paddingVertical: 8, paddingHorizontal: 4 },
  doneText: { color: colors.steel, fontFamily: fonts.bodyBold, fontSize: 13 },
});
